server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://192.168.32.129:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.129:12336/learn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: learn
    password: Lb19931127

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.lubin.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2